FROM debian:bullseye

RUN apt update && apt install -y mariadb-server mariadb-client

RUN apt install -y php php-mysql php-fpm php-curl php-gd php-intl php-mbstring php-soap php-xml php-xmlrpc php-zip

#CMD tail -f /dev/null 
